### ISSUE TITLE
No f_namemax (or f_namelen) in the statvfs structure

### ISSUE THREAD

**Issue by denismo** [terencehonles/fusepy#16]
I've been using fusepy for an implementation of a filesystem and wanted to test the correctness of the implementation using one of the publicly available FS test suites. Unfortunately that did work because as one of the first operations it tries to determine the maximum length of name for the filesystem.

In C API, there is a field in the statfs/statvfs structures which returns the maximum name length. It is not currently present in the structure definition. Surprisingly, even after adding the required fields to the structure declarations in fuse.py I could not get it to work for whatever reason.

**Comment by rncry** [comment]
I had this problem too.. There's a pull request here to fix it:

https://github.com/terencehonles/fusepy/pull/39

**Comment by terencehonles** [comment]
Merged #39
