### ISSUE TITLE
Can't start class of fuse.Operations in multiple processes.

### ISSUE THREAD

**Issue by arthurwozniak** [terencehonles/fusepy#46]
Hello, I'm trying to write own encrypted filesystem with fusepy. I have already done console version and now I'm creating GUI for it. It is pretty simple, just "volume" manager with mount buttons. My idea is that I click on mount button and then program calls fuse.FUSE with appropriate arguments. But it only works for the first mount. If I try to mount second attribute, fuse.FUSE __init__ method fails on following code
`fuse_ops = fuse_operations()`
        `for name, prototype in fuse_operations._fields_:`
            `if prototype != c_voidp and getattr(operations, name, None):`
                `op = partial(self._wrapper, getattr(self, name))`
                `setattr(fuse_ops, name, prototype(op))`

I start thread like this
`
p = Process(target=fuse.FUSE, args=(Filecrypter(self.source_dir, password), self.mount_dir), kwargs=kargs)`
`p.start()`
which should work, in my opinion. That's why I worry if it is not any bug in fuse class. What do you think?

**Comment by eestrada** [comment]
What exception is raised? What is the traceback? Put the failing code in a `try/except` block and print the exception somewhere (a file, the terminal, wherever).

**Comment by arthurwozniak** [comment]
I see I forgot to edit my question. After deeper investigating, problem was unauthorized access to memory, probably because each process p used fuse object from same memory address. Now I run it in thread and everything works. My fault.
