### ISSUE TITLE
Version mismatch on github and pipy

### ISSUE THREAD

**Issue by etiandre** [terencehonles/fusepy#47]
Hi,

The last release listed on github is 2.0.2 [(here)](https://github.com/terencehonles/fusepy/releases) but there is a 2.0.3 version on pipy [here](https://pypi.python.org/pypi/fusepy/) since quite some time. Github is described as the only official release source, so it would be nice if version numbers catched up.

**Comment by rianhunter** [comment]
+1 waiting on this!

**Comment by terencehonles** [comment]
Thanks, forgot to tag the commit, but I bumped the project to `2.0.4` with a couple small changes that were merged
